dist: xenial

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO="Django==2.1.1"
  - DJANGO="Django==2.0.8"
  - DJANGO="Django==1.11.15"

matrix:
  exclude:
    - env: DJANGO="Django==2.1.1"
      python: 2.7
    - env: DJANGO="Django==2.1.1"
      python: 3.4
    - env: DJANGO="Django==2.0.8"
      python: 2.7
    - env: DJANGO="Django==1.11.15"
      python: 3.7

install:
  - pip install $DJANGO
  - pip install factory-boy
  - pip install coveralls
  - python setup.py develop

script:
  - cd example_project; coverage run manage.py test

after_success:
  - coveralls


